version: '3.9'
services:
  proxy:
    image: envoyproxy/envoy:v1.20.0
    environment:
      NODE_ENV: development
      loglevel: debug
    ports:
      - 8080:8080
      - 9901:9901
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8084:8084
    networks:
      - envoymesh
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
networks:
  envoymesh: {}